appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32cadf302eb707003c078e
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: QIOSpPs+ldKMu+n94tt//MTLq3jz1tjrSGPDye2kAQOT2ZYAWGJbXnq84o1mMy8z4OpL1x74hHSUSLicMIz5uxJH2H1ip4JQSd9IAvi8PPcTr/H2AAFzNCITdJ+DKpCKL1BAc+qPwxTyi5cWEPnbzbt29CNN+UvXAuv2OLzjNd5PSVfPF42mQza3qCX1ClNVSwiLyv3XT13Ly5Kx6jxFooYiO5GnWpMdsyIJJjNsZz0m4nfkY0efta4kHlW01emIQjRoE0xUTP54vwLEEm0nLi0lreRve3CmQfHXVS/PUcysrQNiqh4VeUaH+PYyvR7/C0sLSKYxHVE0PJNHBbuC1dw4sXr/WZLwOXZ92QQWzoYCl3b2Ar9bJ1KShVdFZq9WdwXDHWiZLJjAUVhZUvcvo+/JChpobit4PidGJxZmES10IZwB8byDetrwLUx4oX7vTrAdGLtx39rGYXIt4aJWfIlB/Sd6Q6lwZ1NLHJLiu3nEiN7aE4tSZtlWyURJtrBQgiA3vdbdE1LhXh+rlTpKi/ga+3bDaPbbdVzVPnyAbepkA+htrHjkUzC5vY6xi6ZESjfnT7zFmhpPp+rLYvAdHI0pRv81vChqdQNTfoemQg3a3yZcVFVQQOrV8QZ9EtVaW5apSDg+3Ujriau/AOtM/jITjm0pinSLPfqf0SpqOWQ=}
